# Generated by Django 3.0.5 on 2020-04-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hamburguesa',
            name='ingredientes',
            field=models.ManyToManyField(to='apiapp.Ingrediente'),
        ),
        migrations.AlterField(
            model_name='hamburguesa',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Hamburguesa_Ingrediente',
        ),
    ]
